# create your drupal and postgres config here, based off the last assignment
services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/theme
      - drupal-themes:/var/www/html/sites
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - drupal-data:/var/lib/postgresql/data
 

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: